name: Build and Deploy Docker

on:
  push:
    tags:
      - '*'

jobs:
  build-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build docker image and push to GitHub Registry
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  auto-deploy-docker-job:
    runs-on: ubuntu-latest
    needs: build-docker-image-job
    environment: production
    env:
      SERVER_IP: '157.90.230.179'
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      CONTAINER_NAME: ${{ github.actor }}
      SERVER_PORT: 8177
      DOCKER_IMAGE_URL: 'ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.ref_name }}'
    steps:
      - name: Executing remote ssh using password
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          password: ${{ env.SERVER_PASSWORD }}
          port: '22'
          script: |
            docker -v