name: Frontend Workshop React

on: 
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'chore/**'
      - main # อย่าลืมลบกรณีใช้งานจริง
  pull_request:
    branches:
      - main

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set Nodejs version to 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check lint
        run: npm run lint

  build-job:
    runs-on: ubuntu-latest
    needs: lint-job #รอให้ lint job ผ่านก่อนค่อยทำ
    steps:
      - uses: actions/checkout@v5
      - name: Set Nodejs version to 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check build app
        run: npm run build

  build-job-matrix:
    runs-on: ubuntu-latest
    needs: lint-job #รอให้ lint job ผ่านก่อนค่อยทำ
    strategy:
      matrix:
        # os: [ubuntu-latest, window-latest]
        node-version: [22.x, 24.x]
    steps:
      - uses: actions/checkout@v5
      - name: Set Nodejs version to ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check build app
        run: npm run build